[package]
authors = ["mdrokz <mohammadmunshi@gmail.com>"]
name = "llama_cuda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama_cpp_rs = {path = "../../", features = ["cuda"]}
strfmt = "0.2.4"
